[package]
name = "whelk"
version = "0.1.0"
authors = ["Jim Balhoff <balhoff@renci.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
horned-owl = "0.11.0"
itertools = "0.10.3"
